export const citiesList = [
    {
        id:"1",
        label:"Kanpur",
        value:"Kanpur",
    },
    {
        id:"2",
        label:"Pune",
        value:"Pune",
    },
    {
        id:"3",
        label:"Mumbai",
        value:"Mumbai",
    },
    {
        id:"4",
        label:"Chandigarh",
        value:"Chandigarh",
    },
    {
        id:"5",
        label:"Karnatka",
        value:"Karnatka",
    },
    {
        id:"6",
        label:"Ranchi",
        value:"Ranchi",
    },
    {
        id:"7",
        label:"Chennai",
        value:"Chennai",
    },
    {
        id:"8",
        label:"Hyderabad",
        value:"Hyderabad",
    },
];