 export let citysList =[
         {
            id:"1",
            cityName:"Kanpur"
         },
         {
            id:"2",
            cityName:"Lucknow"
         },
         {
            id:"3",
            cityName:"Chandigarh"
         },
         {
            id:"4",
            cityName:"Mumbai"
         },
         {
            id:"5",
            cityName:"Pune"
         },
         {
            id:"6",
            cityName:"Banglore"
         },
         {
            id:"7",
            cityName:"Other"
         },
];

